export const EDS_Maintenance_Tasks = [
  {
    "id": 1,
    "description": "Exhaust valve - removal and installation",
    "component": 4,
    "tools": "2 Sling 94049A",
    "documentation": "177",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 1,
        "pos": "",
        "partNumber": "AX 27500",
        "description": "Exhaust valve, complete",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 2,
        "pos": "",
        "partNumber": "AX 27502",
        "description": "Valve cage, complete",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 3,
        "pos": "",
        "partNumber": "AX 27504",
        "description": "Guide bush",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 4,
        "pos": "",
        "partNumber": "AX 27506",
        "description": "Distance ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 5,
        "pos": "",
        "partNumber": "AX 27508",
        "description": "Gasket square to AX 27509",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 6,
        "pos": "",
        "partNumber": "AX 27509",
        "description": "Blind flange square",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 7,
        "pos": "",
        "partNumber": "AX 27510",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 8,
        "pos": "",
        "partNumber": "AX 27511",
        "description": "Gasket to AX 27510",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 9,
        "pos": "",
        "partNumber": "AX 27514",
        "description": "O-ring for AX 27516",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 10,
        "pos": "",
        "partNumber": "AX 27515",
        "description": "O-ring for AX 27504",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 11,
        "pos": "",
        "partNumber": "AX 27516",
        "description": "Valve seat",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 12,
        "pos": "",
        "partNumber": "AX 27518",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 13,
        "pos": "",
        "partNumber": "AX 27519",
        "description": "Throttle screw",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 14,
        "pos": "",
        "partNumber": "AX 27521",
        "description": "Upper housing, complete",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 15,
        "pos": "",
        "partNumber": "AX 27522",
        "description": "Throttle",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 16,
        "pos": "",
        "partNumber": "AX 27523",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 17,
        "pos": "",
        "partNumber": "AX 27528",
        "description": "Damper",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 18,
        "pos": "",
        "partNumber": "AX 27532",
        "description": "Shim ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 19,
        "pos": "",
        "partNumber": "AX 27533",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 20,
        "pos": "",
        "partNumber": "AX 27535",
        "description": "Housing",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 21,
        "pos": "",
        "partNumber": "AX 27547",
        "description": "Elastic bolt",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 22,
        "pos": "",
        "partNumber": "AX 27550",
        "description": "Cup spring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 23,
        "pos": "",
        "partNumber": "AX 27555",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 24,
        "pos": "",
        "partNumber": "AX 27556",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 25,
        "pos": "",
        "partNumber": "AX 27558",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 26,
        "pos": "",
        "partNumber": "AX 27560",
        "description": "Rod joint ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 27,
        "pos": "",
        "partNumber": "AX 27562",
        "description": "Gasket",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 28,
        "pos": "",
        "partNumber": "AX 27600",
        "description": "Exhaust valve spindle with rotation wing",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 29,
        "pos": "",
        "partNumber": "AX 27521",
        "description": "Upper housing, complete",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 30,
        "pos": "",
        "partNumber": "AX 27525",
        "description": "Piston guide",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 31,
        "pos": "",
        "partNumber": "AX 27526",
        "description": "Outside piston",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 32,
        "pos": "",
        "partNumber": "AX 27527",
        "description": "Inside piston",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 33,
        "pos": "",
        "partNumber": "AX 27530",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 34,
        "pos": "",
        "partNumber": "AX 27531",
        "description": "Washer",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 35,
        "pos": "",
        "partNumber": "AX 27535",
        "description": "Housing",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 36,
        "pos": "",
        "partNumber": "AX 27540",
        "description": "Piston",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 37,
        "pos": "",
        "partNumber": "AX 27541",
        "description": "Transmitter housing",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 38,
        "pos": "",
        "partNumber": "AX 27544",
        "description": "Valve stroke sensor",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 39,
        "pos": "",
        "partNumber": "AX 27546",
        "description": "Valve cotter 2-parts",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 40,
        "pos": "",
        "partNumber": "AX 27549",
        "description": "Spring dowel pin",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 41,
        "pos": "",
        "partNumber": "AX 27551",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 42,
        "pos": "",
        "partNumber": "AX 27552",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 43,
        "pos": "",
        "partNumber": "AX 27553",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 44,
        "pos": "",
        "partNumber": "AX 27554",
        "description": "Piston joint ring",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 45,
        "pos": "",
        "partNumber": "AX 27557",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 46,
        "pos": "",
        "partNumber": "AX 27559",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 47,
        "pos": "",
        "partNumber": "AX 27561",
        "description": "Non return valve",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      },
      {
        "maintenanceList": null,
        "id": 48,
        "pos": "",
        "partNumber": "AX 27563",
        "description": "Spring dowel pin",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 1
      }
    ]
  },
  {
    "id": 2,
    "description": "Replacement of proximity sensor",
    "component": 25,
    "tools": "-",
    "documentation": "443",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 49,
        "pos": "",
        "partNumber": "AX 92230",
        "description": "Sensor adapter, complete",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 50,
        "pos": "",
        "partNumber": "AX 92233",
        "description": "Crank angle mark",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 51,
        "pos": "",
        "partNumber": "AX 92234",
        "description": "Crank angle mark",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 52,
        "pos": "",
        "partNumber": "AX 92235",
        "description": "Proximity sensor",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 53,
        "pos": "",
        "partNumber": "AX 92236",
        "description": "Plug with cable",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 54,
        "pos": "",
        "partNumber": "AX 92238",
        "description": "O-ring",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 55,
        "pos": "",
        "partNumber": "AX 92239",
        "description": "Locking plate",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      },
      {
        "maintenanceList": null,
        "id": 56,
        "pos": "",
        "partNumber": "AX 92241",
        "description": "Spring dowel pin",
        "assembly": "0",
        "inventory": "0",
        "page": "340",
        "maintenanceTask": 2
      }
    ]
  },
  {
    "id": 3,
    "description": "Injection valve replacement",
    "component": 5,
    "tools": "2 Hexagon head bolt 94270C, 2 Stud bolts 94270D",
    "documentation": "159",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 57,
        "pos": "",
        "partNumber": "AX 27200",
        "description": "Injection valve, complete (IACS)",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 58,
        "pos": "",
        "partNumber": "AX 27200",
        "description": "Injection valve with seals",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 59,
        "pos": "",
        "partNumber": "AX 27210",
        "description": "Tension washer cage, complete",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 60,
        "pos": "",
        "partNumber": "AX 27211",
        "description": "Spring guide",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 61,
        "pos": "",
        "partNumber": "AX 27212",
        "description": "Bush",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 62,
        "pos": "",
        "partNumber": "AX 27213",
        "description": "Cup spring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 63,
        "pos": "",
        "partNumber": "AX 27214",
        "description": "Snap ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 64,
        "pos": "",
        "partNumber": "AX 27215",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      },
      {
        "maintenanceList": null,
        "id": 65,
        "pos": "",
        "partNumber": "AX 27244",
        "description": "Nozzle tip",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 3
      }
    ]
  },
  {
    "id": 4,
    "description": "Stroke sensor installation",
    "component": 4,
    "tools": "-",
    "documentation": "187",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 66,
        "pos": "",
        "partNumber": "AX 27544",
        "description": "Valve stroke sensor",
        "assembly": "",
        "inventory": "",
        "page": "100",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 67,
        "pos": "",
        "partNumber": "AX 93680",
        "description": "Cable socket with flat joint",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 68,
        "pos": "",
        "partNumber": "AX 93681",
        "description": "Flat joint for AX 93680",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 69,
        "pos": "",
        "partNumber": "AX 93685",
        "description": "Cable ducts",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 70,
        "pos": "",
        "partNumber": "AX 93686",
        "description": "Terminal box",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 71,
        "pos": "",
        "partNumber": "AX 93687",
        "description": "Plug with cable",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 72,
        "pos": "",
        "partNumber": "AX 93688",
        "description": "Holder",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 73,
        "pos": "",
        "partNumber": "AX 93691",
        "description": "Cable fitting",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 74,
        "pos": "",
        "partNumber": "AX 93692",
        "description": "Cable fitting",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 75,
        "pos": "",
        "partNumber": "AX 93693",
        "description": "Ring piece",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 76,
        "pos": "",
        "partNumber": "AX 93694",
        "description": "Metallic hose end",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      },
      {
        "maintenanceList": null,
        "id": 77,
        "pos": "",
        "partNumber": "AX 93695",
        "description": "Protection hose",
        "assembly": "",
        "inventory": "",
        "page": "390",
        "maintenanceTask": 4
      }
    ]
  },
  {
    "id": 5,
    "description": "Exhaust valve control unit removal",
    "component": 4,
    "tools": "-",
    "documentation": "351",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 78,
        "pos": "",
        "partNumber": "AX 56120",
        "description": "Exhaust valve control unit, complete (AX 56122 to AX 56150)",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 79,
        "pos": "",
        "partNumber": "AX 56122",
        "description": "Valve control block",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 80,
        "pos": "",
        "partNumber": "AX 56123",
        "description": "Piston",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 81,
        "pos": "",
        "partNumber": "AX 56124",
        "description": "Slide rod",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 82,
        "pos": "",
        "partNumber": "AX 56125",
        "description": "Plug",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 83,
        "pos": "",
        "partNumber": "AX 56126",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 84,
        "pos": "",
        "partNumber": "AX 56127",
        "description": "Non return valve",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 85,
        "pos": "",
        "partNumber": "AX 56128",
        "description": "Back-up ring",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 86,
        "pos": "",
        "partNumber": "AX 56129",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 87,
        "pos": "",
        "partNumber": "AX 56130",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 88,
        "pos": "",
        "partNumber": "AX 56131",
        "description": "Throttle",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 89,
        "pos": "",
        "partNumber": "AX 56132",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 90,
        "pos": "",
        "partNumber": "AX 56135",
        "description": "4/2-wey valve",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 91,
        "pos": "",
        "partNumber": "AX 56136",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 92,
        "pos": "",
        "partNumber": "AX 56140",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 93,
        "pos": "",
        "partNumber": "AX 56141",
        "description": "Distance sleeve",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 94,
        "pos": "",
        "partNumber": "AX 56145",
        "description": "Oil filter, complete (AX 56122 to AX 56150)",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 95,
        "pos": "",
        "partNumber": "AX 56146",
        "description": "Filter holder",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 96,
        "pos": "",
        "partNumber": "AX 56147",
        "description": "Oil filter",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 97,
        "pos": "",
        "partNumber": "AX 56148",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 98,
        "pos": "",
        "partNumber": "AX 56149",
        "description": "Seal",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 99,
        "pos": "",
        "partNumber": "AX 56150",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      },
      {
        "maintenanceList": null,
        "id": 100,
        "pos": "",
        "partNumber": "AX 56152",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "184",
        "maintenanceTask": 5
      }
    ]
  },
  {
    "id": 6,
    "description": "Damper setting",
    "component": 4,
    "tools": "-",
    "documentation": "186",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 101,
        "pos": "",
        "partNumber": "AX 27528",
        "description": "Damper",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 6
      }
    ]
  },
  {
    "id": 7,
    "description": "Valve seat replace / grind",
    "component": 4,
    "tools": "1 Feeler gauge 94122, 1 Valve seat dismantling device 94261, 1 Template 94279, 1 Tool, grinding 94291",
    "documentation": "189",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 102,
        "pos": "",
        "partNumber": "AX 27514",
        "description": "O-ring for AX 27516",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 7
      },
      {
        "maintenanceList": null,
        "id": 103,
        "pos": "",
        "partNumber": "AX 27516",
        "description": "Valve seat",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 7
      },
      {
        "maintenanceList": null,
        "id": 104,
        "pos": "",
        "partNumber": "AX 27555",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 7
      },
      {
        "maintenanceList": null,
        "id": 105,
        "pos": "",
        "partNumber": "AX 27562",
        "description": "Gasket",
        "assembly": "",
        "inventory": "",
        "page": "98",
        "maintenanceTask": 7
      }
    ]
  },
  {
    "id": 8,
    "description": "Fuel pump assemble, disassemble",
    "component": 6,
    "tools": "1 Assembling device 94593 Consisting of: 1 Ring 94593A, 2 Ring (2-part) 94593B, 2 Guide rods 94593C, 2 Screws 94593D, 2 Step rods 94593E, 4 Screws with special nuts 94593F, 4 Screws 94593G, 1 Mandrel (? 70 mm) 94597, 1 Mandrel (? 40 mm) 94597A, 1 Pneum. impact wrench 94598, 2 Extensions 94598A, 1 Socket spanner insert 94598B, 1 Fuel pump rack 94592 Consisting of: 1 Oil tray 94592A, 2 Limiters 94592B, 2 Screws 94592C, 4 Screws 94592D, 2 Screws 94592E, 1 Circlip plier 94007?A41, 1 Handle 94009?M10, 1 Manual ratchet 94016?031, 1 2-part clamping ring 94550, 1 Spindle press 94551, 1 Lifting tool 94552, 1 Rod 94553, 1 Distance piece 94555",
    "documentation": "297",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 106,
        "pos": "",
        "partNumber": "AX 55560",
        "description": "Fuel pump, complete with Fuel pump plunger AX 55640",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 107,
        "pos": "",
        "partNumber": "AX 55561",
        "description": "Lower housing, complete with bush",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 108,
        "pos": "",
        "partNumber": "AX 55563",
        "description": "Upper housing",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 109,
        "pos": "",
        "partNumber": "AX 55564",
        "description": "Bush for AX 55563",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 110,
        "pos": "",
        "partNumber": "AX 55566",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 111,
        "pos": "",
        "partNumber": "AX 55567",
        "description": "Fluted seal ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 112,
        "pos": "",
        "partNumber": "AX 55569",
        "description": "Guide piston",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 113,
        "pos": "",
        "partNumber": "AX 55570",
        "description": "Pump cover",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 114,
        "pos": "",
        "partNumber": "AX 55572",
        "description": "Non return valve, complete",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 115,
        "pos": "",
        "partNumber": "AX 55573",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 116,
        "pos": "",
        "partNumber": "AX 55579",
        "description": "Toothed rack",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 117,
        "pos": "",
        "partNumber": "AX 55580",
        "description": "Regulating sleeve",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 118,
        "pos": "",
        "partNumber": "AX 55587",
        "description": "Guide pin",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 119,
        "pos": "",
        "partNumber": "AX 55588",
        "description": "Intermediate flange",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 120,
        "pos": "",
        "partNumber": "AX 55589",
        "description": "Ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 121,
        "pos": "",
        "partNumber": "AX 55594",
        "description": "Retainig ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 122,
        "pos": "",
        "partNumber": "AX 55598",
        "description": "Guide pin",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 123,
        "pos": "",
        "partNumber": "AX 55599",
        "description": "Covering",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 124,
        "pos": "",
        "partNumber": "AX 55600",
        "description": "Covering",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 125,
        "pos": "",
        "partNumber": "AX 55605",
        "description": "Rod seal ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 126,
        "pos": "",
        "partNumber": "AX 55607",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 127,
        "pos": "",
        "partNumber": "AX 55611",
        "description": "Hexagon socket head screw",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 128,
        "pos": "",
        "partNumber": "AX 55612",
        "description": "Hexagon head bolt",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 129,
        "pos": "",
        "partNumber": "AX 55613",
        "description": "Parallel pin",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 130,
        "pos": "",
        "partNumber": "AX 55617",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 131,
        "pos": "",
        "partNumber": "AX 55618",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 132,
        "pos": "",
        "partNumber": "AX 55621",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 133,
        "pos": "",
        "partNumber": "AX 55624",
        "description": "Lower spring carrier",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 134,
        "pos": "",
        "partNumber": "AX 55625",
        "description": "Connection pin",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 135,
        "pos": "",
        "partNumber": "AX 55626",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 136,
        "pos": "",
        "partNumber": "AX 55640",
        "description": "Fuel pump plunger, complete (Please state plunger diameter)",
        "assembly": "",
        "inventory": "",
        "page": "168",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 137,
        "pos": "",
        "partNumber": "AX 55569",
        "description": "Guide piston",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 138,
        "pos": "",
        "partNumber": "AX 55570",
        "description": "Pump cover",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 139,
        "pos": "",
        "partNumber": "AX 55572",
        "description": "Non return valve, complete",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 140,
        "pos": "",
        "partNumber": "AX 55575",
        "description": "Upper spring carrier",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 141,
        "pos": "",
        "partNumber": "AX 55582",
        "description": "Roller with bush and roller pin, complete",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 142,
        "pos": "",
        "partNumber": "AX 55584",
        "description": "Pressure disc",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 143,
        "pos": "",
        "partNumber": "AX 55585",
        "description": "Locating pin",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 144,
        "pos": "",
        "partNumber": "AX 55586",
        "description": "Retaining screw",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 145,
        "pos": "",
        "partNumber": "AX 55591",
        "description": "Compression spring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 146,
        "pos": "",
        "partNumber": "AX 55592",
        "description": "Hexagon socket head screw",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 147,
        "pos": "",
        "partNumber": "AX 55595",
        "description": "Rod joint ring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 148,
        "pos": "",
        "partNumber": "AX 55596",
        "description": "Oil pipe inlet",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 149,
        "pos": "",
        "partNumber": "AX 55597",
        "description": "Oil pipe drain",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 150,
        "pos": "",
        "partNumber": "AX 55601",
        "description": "Orifice",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 151,
        "pos": "",
        "partNumber": "AX 55602",
        "description": "Adapter piece",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 152,
        "pos": "",
        "partNumber": "AX 55603",
        "description": "Fluted seal ring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 153,
        "pos": "",
        "partNumber": "AX 55604",
        "description": "Fluted seal ring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 154,
        "pos": "",
        "partNumber": "AX 55606",
        "description": "Seal",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 155,
        "pos": "",
        "partNumber": "AX 55608",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 156,
        "pos": "",
        "partNumber": "AX 55615",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 157,
        "pos": "",
        "partNumber": "AX 55616",
        "description": "Circlip",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 158,
        "pos": "",
        "partNumber": "AX 55619",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      },
      {
        "maintenanceList": null,
        "id": 159,
        "pos": "",
        "partNumber": "AX 55620",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "170",
        "maintenanceTask": 8
      }
    ]
  },
  {
    "id": 9,
    "description": "Pressure Control Valve removal, check, installation",
    "component": 26,
    "tools": "1 HP oil pump 94931, 1 HP hose 94935, 1 Pressure gage 94934A, 1 PCV test block with tube 94556",
    "documentation": "319",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 160,
        "pos": "",
        "partNumber": "AX 55725",
        "description": "Valve block, complete (AX 55726 to AX 55750)",
        "assembly": "",
        "inventory": "",
        "page": "176",
        "maintenanceTask": 9
      },
      {
        "maintenanceList": null,
        "id": 161,
        "pos": "",
        "partNumber": "AX 55726",
        "description": "Pressure control valve, complete",
        "assembly": "",
        "inventory": "",
        "page": "176",
        "maintenanceTask": 9
      },
      {
        "maintenanceList": null,
        "id": 162,
        "pos": "",
        "partNumber": "AX 55727",
        "description": "Valve block",
        "assembly": "",
        "inventory": "",
        "page": "176",
        "maintenanceTask": 9
      },
      {
        "maintenanceList": null,
        "id": 163,
        "pos": "",
        "partNumber": "AX 55728",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "176",
        "maintenanceTask": 9
      }
    ]
  },
  {
    "id": 10,
    "description": "Gas admission valve disassembly",
    "component": 23,
    "tools": "1 Eye bolt 94045?M10, 1 Pressure reducing valve 94214B, 1 Dismantling tool 94214 1 Assembly tool 94023A, 1 Handle 94214A, 2 M10 Screws",
    "documentation": "149",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 164,
        "pos": "",
        "partNumber": "FX 21400",
        "description": "Gas admission valve, complete (FX 21404 to FX 21435)",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 165,
        "pos": "",
        "partNumber": "FX 21403",
        "description": "Cover",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 166,
        "pos": "",
        "partNumber": "FX 21404",
        "description": "Gas admission valve, complete with valve guide and valve spindle",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 167,
        "pos": "",
        "partNumber": "FX 21405",
        "description": "Housing",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 168,
        "pos": "",
        "partNumber": "FX 21406",
        "description": "Cover",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 169,
        "pos": "",
        "partNumber": "FX 21408",
        "description": "Spring carrier",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 170,
        "pos": "",
        "partNumber": "FX 21409",
        "description": "Piston",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 171,
        "pos": "",
        "partNumber": "FX 21410",
        "description": "Valve cotter 2 -parts",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 172,
        "pos": "",
        "partNumber": "FX 21414",
        "description": "Compression spring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 173,
        "pos": "",
        "partNumber": "FX 21415",
        "description": "Rail valve, complete (box) (with rail valve, screws ,O-ring)",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 174,
        "pos": "",
        "partNumber": "FX 21416",
        "description": "Gasket",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 175,
        "pos": "",
        "partNumber": "FX 21417",
        "description": "Valve stroke sensor, complete",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 176,
        "pos": "",
        "partNumber": "FX 21418",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 177,
        "pos": "",
        "partNumber": "FX 21420",
        "description": "Sleeve",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 178,
        "pos": "",
        "partNumber": "FX 21421",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 179,
        "pos": "",
        "partNumber": "FX 21422",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 180,
        "pos": "",
        "partNumber": "FX 21423",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 181,
        "pos": "",
        "partNumber": "FX 21425",
        "description": "Spring dowel pin",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 182,
        "pos": "",
        "partNumber": "FX 21426",
        "description": "Spring dowel pin",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 183,
        "pos": "",
        "partNumber": "FX 21427",
        "description": "Filter, complete with seal",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 184,
        "pos": "",
        "partNumber": "FX 21428",
        "description": "Seal for FX 21427",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 185,
        "pos": "",
        "partNumber": "FX 21429",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 186,
        "pos": "",
        "partNumber": "FX 21430",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 187,
        "pos": "",
        "partNumber": "FX 21431",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 188,
        "pos": "",
        "partNumber": "FX 21432",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 189,
        "pos": "",
        "partNumber": "FX 21433",
        "description": "Screw plug",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 190,
        "pos": "",
        "partNumber": "FX 21434",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 191,
        "pos": "",
        "partNumber": "FX 21435",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 192,
        "pos": "",
        "partNumber": "FX 21436",
        "description": "Screw Plug",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 193,
        "pos": "",
        "partNumber": "FX 21437",
        "description": "By-pass",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 194,
        "pos": "",
        "partNumber": "FX 21438",
        "description": "Hexagon socket head cop screw",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      },
      {
        "maintenanceList": null,
        "id": 195,
        "pos": "",
        "partNumber": "FX 21439",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "92",
        "maintenanceTask": 10
      }
    ]
  },
  {
    "id": 11,
    "description": "Pilot injection valve remove and install",
    "component": 23,
    "tools": "2 Hexagon head bolt 94270C, 2 Stud bolts 94270D",
    "documentation": "175",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 196,
        "pos": "",
        "partNumber": "FX 27900",
        "description": "Connection flange",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 197,
        "pos": "",
        "partNumber": "FX 27903",
        "description": "Prechamber, complete (conical, incl FX 27905)",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 198,
        "pos": "",
        "partNumber": "FX 27905",
        "description": "Seal (conical)",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 199,
        "pos": "",
        "partNumber": "FX 27907",
        "description": "Dowel pin",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 200,
        "pos": "",
        "partNumber": "FX 27908",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 201,
        "pos": "",
        "partNumber": "FX 27909",
        "description": "O-ring",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 202,
        "pos": "",
        "partNumber": "FX 27915",
        "description": "Pilot injection valve with seals",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 203,
        "pos": "",
        "partNumber": "FX 27918",
        "description": "Distance sleeve",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 204,
        "pos": "",
        "partNumber": "FX 27919",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 205,
        "pos": "",
        "partNumber": "FX 27921",
        "description": "Hexagon socket head cap screw",
        "assembly": "",
        "inventory": "",
        "page": "110",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 206,
        "pos": "",
        "partNumber": "FX 27925",
        "description": "Coupling nut",
        "assembly": "",
        "inventory": "",
        "page": "112",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 207,
        "pos": "",
        "partNumber": "FX 96235",
        "description": "Pilot injector valve with seals",
        "assembly": "",
        "inventory": "",
        "page": "112",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 208,
        "pos": "",
        "partNumber": "FX 96237",
        "description": "Spare kit seals with flat seal",
        "assembly": "",
        "inventory": "",
        "page": "112",
        "maintenanceTask": 11
      },
      {
        "maintenanceList": null,
        "id": 209,
        "pos": "",
        "partNumber": "FX 96238",
        "description": "Spare kit seals with conical seal",
        "assembly": "",
        "inventory": "",
        "page": "112",
        "maintenanceTask": 11
      }
    ]
  },
  {
    "id": 12,
    "description": "Scavenge air cooler removal & installation",
    "component": 8,
    "tools": "2 Trolleys (WLL3000kg) 94021, 1 Spur-geared chain block 94017-013 (WLL5000kg), 1 Manual ratchet (WLL2500kg) 94016-011, 1 Manual ratchet (WLL1000kg) 94016-006, 1 Left Support 94663A, 1 Right Support 94663B, 2 Safety lugs 94663C, 2 Safety chains 94663D, 1 Support 94663I, 1 Chain 94019A, 6 Lugs 94048?M30, 1 Chain 94019C",
    "documentation": "367",
    "spareParts": [
      {
        "maintenanceList": null,
        "id": 210,
        "pos": "",
        "partNumber": "AX 66060",
        "description": "Scavenge air cooler",
        "assembly": "",
        "inventory": "",
        "page": "190",
        "maintenanceTask": 12
      }
    ]
  }
];
